#访问根路径

#应用名称
spring:
  application:
    name: jsoup
  #数据库相关配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.19.2.155:3306/story
#    #url: jdbc:mysql://localhost:3306/story
#    username: root
#    password: hi&U4y6glUeh
#    max-idle: 10
#    max-wait: 10000
#    min-idle: 5
#    initial-size: 5
#    type: com.alibaba.druid.pool.DruidDataSource

#访问端口号
server:
  port: 9011

  #编码格式
  tomcat:
    uri-encoding: utf-8
  #session生命周期

  servlet:
    session:
      timeout: 30m
#生产环境需注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl










