#访问根路径

#应用名称
spring:
  application:
    name: provider
  rabbitmq:
    virtual-host: /
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

mq:
  basic:
    info:
      objectqueue:
        name: object_queue
      queue:
        name: queue_name
      objecetexchange:
        name: object_exchange_name
      exchange:
        name: exchange_name
      routing:
        key:
          name: key_name
        objectkey:
          name: object_key_name


      fanout:
        queuename: AfanoutA
        queuenameb: fanoutB
        exchange: exchange
        topicexchange: topicexchange
        bindkeya: AfaountA
        bindkeyb: faountB
        bindkey: A*
      dead:
        queuename: deadQueueNameAA
        realqueue: realQueueNameAA
        topicexchange: deadtopicexchange1
        deadexchange: deadexchange1
        binddeadkeya: deadKeyAA
        bindkey: deadKeyAA
#  #数据库相关配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/story
#    username: root
#    password: lcy123456
#    max-idle: 10
#    max-wait: 10000
#    min-idle: 5
#    initial-size: 5
#    type: com.alibaba.druid.pool.DruidDataSource
##redis 配置
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    timeout: 30000
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        min-idle: 0
#        max-idle: 8
#    password: null
#访问端口号
server:
  port: 8091

  #编码格式
  tomcat:
    uri-encoding: utf-8
  #session生命周期

  servlet:
    session:
      timeout: 30m
#生产环境需注释掉
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl










