#访问根路径

#应用名称
spring:
  application:
    name: zookeeper

zk:
  host: 127.0.0.1:2181
  namespace: middle_distributeLock
  #数据库相关配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/story
#    username: root
#    password: lcy123456
#    max-idle: 10
#    max-wait: 10000
#    min-idle: 5
#    initial-size: 5
#    type: com.alibaba.druid.pool.DruidDataSource
#redis 配置
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    timeout: 30000
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        min-idle: 0
#        max-idle: 8
#    password: null
#访问端口号
server:
  port: 8012

  #编码格式
  tomcat:
    uri-encoding: utf-8
  #session生命周期

  servlet:
    session:
      timeout: 30m











